name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    uses: joeckr/ci-templates/.github/workflows/semantic.yml@1180cc83e239b1f1ff2b2592baaa7e8c64465816  # v1.14.0

  matrix-build:
    needs: [release]
    if: needs.release.outputs.released == 'true' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
      security-events: write
    uses: joeckr/ci-templates/.github/workflows/build-oci-custom.yml@1180cc83e239b1f1ff2b2592baaa7e8c64465816  # v1.14.0
    with:
      image: "oci-custom"

  helm:
    needs: [release]
    if: needs.release.outputs.released == 'true' || github.event_name == 'workflow_dispatch'
    permissions:
      contents: read
      packages: write
    uses: joeckr/ci-templates/.github/workflows/push-helm-ghcr.yml@1180cc83e239b1f1ff2b2592baaa7e8c64465816  # v1.14.0
    with:
      charts-dir: 'chart'
